Add stub checklist

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -25,16 +25,18 @@ url="$2"
 
 zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
 ROOT_DIR=$(git rev-parse --show-toplevel)
+cd $ROOT_DIR
+ROOT_DIR="."
 
 while read local_ref local_oid remote_ref remote_oid
 do
-	if test "$local_oid" = "$zero"
-	then
+	if test "$local_oid" = "$zero" 
+  then
 		# Handle delete
 		:
 	else
-		if test "$remote_oid" = "$zero"
-		then
+		if test "$remote_oid" = "$zero" 
+    then
 			# New branch, examine all commits
 			range="$local_oid"
 		else
@@ -43,8 +45,6 @@ do
 		fi
 
     changedFiles=$(git diff-tree --no-commit-id --name-only $range -r)
-    echo "CHANGED FILES"
-    echo $changedFiles
 		# Check for WIP commit
     testDirs=()
     for file in $changedFiles
@@ -55,17 +55,28 @@ do
         current=$(dirname $current)
         if [ -d "${ROOT_DIR}/${current}/${TEST_DIR_NAME}/" ]
         then
-          echo "PUSHING:" "${ROOT_DIR}/${current}/${TEST_DIR_NAME}/"
-          testDirs+=("${ROOT_DIR}/${current}/${TEST_DIR_NAME}/")
           testDirs+=("${ROOT_DIR}/${current}/${TEST_DIR_NAME}/")
         fi
       done
       #Remove duplicates
     done
-    echo "TEST DIRS:" $testDirs
     #remove duplicates
-    testDirs=$(echo $testDirs | tr ' ' '\n' | sort -nu) 
-    echo $testDirs
+    unique_testDirs=($(echo "${testDirs[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
+    for dir in ${unique_testDirs[@]}
+    do
+      if [[ -f "${dir}run.sh" ]]
+      then
+        ${dir}run.sh
+        errorCode=$?
+        if [[ -z $errorCode ]]
+        then
+          echo "TEST SUITE PASSED AT: ${dir}" 
+        else
+          echo >&2 "TEST SUITE FAILED AT: ${dir}" 
+          exit $errorCode
+        fi
+      fi
+    done
     exit 1
 	fi
 done
