Refinements discovered from second build of mychips.net

diff --git a/build/host/setup b/build/host/setup
--- a/build/host/setup
+++ b/build/host/setup
@@ -1,5 +1,6 @@
 #!/bin/bash
 #Configure a cloud Chip Service Provider
+#DNS should already be resolving to the correct IP before running certbot
 #Copyright MyCHIPs.org; See license in root of this package
 # -----------------------------------------------------------------------------
 # Prior to use, build a cloud server and get the hostname and IP number
@@ -15,6 +16,11 @@ mode=prod
 key_file=siteKey.pem
 cert_file=siteCert.pem
 dkim_file=dkim_private.pem
+dkim_pub=dkim_public.b64
+ssh_pub="$HOME/.ssh/id_rsa.pub"
+ssh_user=root
+read language encoding junk <<<$(echo $locale |tr . ' ')	#;echo "language:$language encoding:$encoding"
+all=("hostname","timezone","packages","locale","admin","node","postgres","certbot","mychips","systemd","mailcerts","sendmail","config")
 
 oargs="$@"
 pargs=()
@@ -23,61 +29,107 @@ while [[ $# -gt 0 ]]; do		#Parse command line
     -a|--admin) mychips_admin="$2"; shift;;
     -d|--devel) mode="devel";;
     -i|--ip) csp_ip="$2"; shift;;
+    -h|--host) csp_host="$2"; shift;;
     -l|--locale) csp_locale="$2"; shift;;
     -z|--zone) csp_zone="$2"; shift;;
     *) pargs+=("$1");;
   esac
   shift
 done
+if [ -z "${pargs[0]}" ]; then		#If no modules specified, default to all
+  pargs=${all[@]}
+fi
 set -- "${pargs[@]}"			#Restore positional arguments
 
-if [ -z "$1" ]; then			#Hostname is first parameter
+if [ -z "$csp_host" ]; then		#Hostname is first parameter
   echo 'You must supply a host domain name'
   exit 1
-else
-  csp_host="$1"
 fi
 
 if [ -z "$csp_ip" ]; then		#Need to fetch the IP number?
   csp_ip="$(dig +short $csp_host)"
 fi					#;echo "host:$csp_host ip:$csp_ip"
 
-(echo "csp_host=$csp_host"
-  cat setup-hostname) | ssh root@${csp_ip} 'bash -s'
+runit() {				echo "Running module: $1"
+  local mod="$1"; shift
+  if [ ! -f setup-"$mod" ]; then
+    echo "Can't find module file: setup-$mod"; exit 1
+  fi
+  (
+    for v in $*; do			#Add custom variables
+      eval "val=\$$v"
+      echo "$v=$val"
+    done
+    echo "mode=$mode"			#All modules get these variables
+    echo "mychips_admin=$mychips_admin"
+    echo "csp_host=$csp_host"
+    cat setup-"$mod"
+  ) | ssh $ssh_user@${csp_ip} 'bash -s'
+}
 
-(echo "csp_zone=$csp_zone"
-  cat setup-timezone) | ssh root@${csp_ip} 'bash -s'
+run_timezone() {
+  runit timezone csp_zone
+}
 
-(echo "mode=$mode"
-  cat setup-packages) | ssh root@${csp_ip} 'bash -s'
+run_locale() {
+  runit locale language encoding
+}
 
-read language encoding junk <<<$(echo $locale |tr . ' ')	#;echo "language:$language encoding:$encoding"
-(echo "language=$language encoding=$encoding"
-  cat setup-locale) | ssh root@${csp_ip} 'bash -s'
+run_admin() {
+  runit admin mychips_admin
+  if [ ! -f $ssh_pub ]; then		#Make sure the user has an ssh key
+    ssh-keygen
+  fi
+  if ssh ${mychips_admin}@${csp_ip} true 2>/dev/null; then
+    echo "ssh connection for $mychips_admin appears to work"
+  elif [ ! -f "$ssh_pub" ]; then
+    echo "Can't find ssh key file: $ssh_pub"
+    exit 1
+  else
+    echo "Attempting to register ssh key for user: $mychips_admin"
+    cat $ssh_pub |
+      ssh root@$csp_ip \ "
+        mkdir -p /home/${mychips_admin}/.ssh
+        tee -a /home/${mychips_admin}/.ssh/authorized_keys
+        chown -R ${mychips_admin}.${mychips_admin} /home/${mychips_admin}/.ssh
+      "
+  fi
+}
 
-if ! (echo "mychips_admin=$mychips_admin"
-    cat setup-admin) | ssh root@${csp_ip} 'bash -s'; then
-  echo -n "Input a password for ${mychips_admin}: "; read -s pwd	#;echo pwd:$pwd
-  ssh root@${csp_ip} "passwd $mychips_admin" <<<"$(echo $pwd; echo $pwd)"
-  echo " Setting up automatic ssh connection key for ${mychips_admin}"
-  expect \
-    -c "spawn ssh-copy-id ${mychips_admin}@${csp_ip}" \
-    -c "expect { password:}" \
-    -c "send \"$pwd\n\"" \
-    -c "expect eof"
-fi
+run_node() {
+  runit node node_version
+}
 
-(echo "node_version=$node_version"
-  cat setup-node) | ssh root@${csp_ip} 'bash -s'
+run_mychips() {
+  ssh_user=$mychips_admin runit mychips
+}
 
-(echo "mode=$mode csp_host=$csp_host"
-  cat setup-mychips) | ssh ${mychips_admin}@${csp_ip} 'bash -s'
+run_mailcerts() {
+  ssh_user=$mychips_admin runit mailcerts dkim_file dkim_pub
+}
 
-(echo "mode=$mode"
-  cat setup-postgres) | ssh root@${csp_ip} 'bash -s'
+run_config() {
+  ssh_user=$mychips_admin runit config
+}
 
-(echo "mode=$mode csp_host=$csp_host mychips_admin=$mychips_admin key_file=$key_file cert_file=$cert_file"
-  cat setup-certbot) | ssh root@${csp_ip} 'bash -s'
+run_certbot() {
+  runit certbot key_file cert_file
+}
 
-(echo "mode=$mode mychips_admin=$mychips_admin key_file=$key_file cert_file=$cert_file dkim_file=$dkim_file"
-  cat setup-systemd) | ssh root@${csp_ip} 'bash -s'
+run_systemd() {
+  runit systemd key_file cert_file dkim_file
+}
+
+#echo "modules:$*"			#;exit
+for m in $*; do				#echo "func:$m $(type -t run_$m)"
+  if [[ $(type -t run_$m) == function ]]; then
+    cmd=run_$m				#Have local function
+  else
+    cmd="runit $m"			#Just run it remotely with defaults
+  fi
+  if ! $cmd; then
+    echo "Module $m exited with an error"
+    exit 1
+  fi
+  shift
+done
diff --git a/build/host/setup-sendmail b/build/host/setup-sendmail
--- a/build/host/setup-sendmail
+++ b/build/host/setup-sendmail
@@ -1,40 +1,38 @@
-# Setup sendmail for communicating with users
+# Setup sendmail as root
 # -------------------------------
-# A good resource for dkim:
-#  https://www.mailhardener.com/kb/how-to-create-a-dkim-record-with-openssl
-#  
+mail_condir="/etc/mail"
+config="sendmail.mc"
+
 if which sendmail >/dev/null; then
   echo "Found installed sendmail"
 else
-  apt-get install sendmail
+  apt-get install sendmail mailutils
 fi							#;echo "cwd:$(pwd)"
 
-pkildir=$(find . -type d -path '*/mychips/pki/local')	#;echo "pkildir:$pkildir"
-if [ -z "$pkildir" -o ! -d "$pkildir" ] || ! cd "$pkildir"; then
-  echo "Can't find key storage folder: mychips/pki/local"
+if ! cd $mail_condir; then
+  echo "Can't find: $mail_condir"
   exit 1
-fi							#;echo "In; $pkildir, $(pwd)"
-
-if [ -f dkim_private.pem ]; then
-  echo "Found existing dkim private key file"
-else
-  openssl genrsa -out dkim_private.pem 2048
 fi
 
-if [ -f dkim_public.b64 ]; then
-  echo "Found existing dkim public key file"
-else
-  openssl rsa -in dkim_private.pem -pubout -outform der 2>/dev/null \
-    | openssl base64 -A \
-    > dkim_public.b64
+if [ ! -f "$config" ]; then
+  echo "Can't find: $mail_condir/$config"
+  exit 1
 fi
 
-key="mychips._domainkey.$(hostname)"		#;echo "key:$key"
-founddkim=$(dig +short TXT $key)
-if [ -z "$founddkim" ]; then
-  echo "Example DNS dkim record: $key"
-  echo "v=DKIM1; p=$(cat dkim_public.b64)"
-else
-  echo "Found dkim record with dns"
+if [ ! -f ${config}.org ]; then
+  echo "Making backup of: $mail_condir/$config"
+  cp $config $config.org
 fi
 
+if ! grep 'DAEMON_OPTIONS.*smtp.*127' sendmail.mc >/dev/null; then
+  echo "Sendmail appears to be configured"
+  exit 0
+fi
+
+cat <<"EOF" | patch $config
+57c57
+< DAEMON_OPTIONS(`Family=inet,  Name=MTA-v4, Port=smtp, Addr=127.0.0.1')dnl
+---
+> DAEMON_OPTIONS(`Family=inet,  Name=MTA-v4, Port=smtp')dnl
+EOF
+systemctl restart sendmail
