Update simulator for latest features

diff --git a/test/sim/simdock b/test/sim/simdock
--- a/test/sim/simdock
+++ b/test/sim/simdock
@@ -8,8 +8,8 @@
 #Initialize
 #-------------------------------------------------------------------------------
 this="$(basename ${BASH_SOURCE})"
-mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";	#echo "mypath:$mypath"
-source $mypath/config.dock
+mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";	#echo "mypath:$mypath"; exit 0
+source $mypath/config.dock				#Default configuration
 checkContext						#Check docker context
 
 pargs=()						#Will hold positional arguments
@@ -28,22 +28,15 @@ done
 set -- "${pargs[@]}"					#Restore positional arguments
 command="$1"; shift
 
-mychips="$mypath"					#Get our bearings in the filesystem
-mysim=""
-while [[ $path != / ]]; do				#Find first bin dir above me
-  if find "$mychips" -maxdepth 1 -mindepth 1 -type d -name bin | grep -q .; then
-    break
-  fi
-  mysim="$(basename $mychips)/${mysim}"			#Find simulation directory
-  mychips="$(cd $mychips/.. && pwd)"
-done
+mychips="$(git rev-parse --show-toplevel)"		#Repo main directory
+mysim="${mypath#$mychips/}"
 
-if [ "$(basename "$mychips")" != "mychips" ]; then
-  echo "Can't find mychips main directory"
+#echo "cwd:$(pwd) mychips:$mychips mypath:$mypath mysim:$mysim sites:$sites"; exit 0
+if ! cd $mychips; then
+  echo "Can't find main directory: $mychips"
   exit 1
 fi
 maxsite=$(expr $sites - 1)
-#echo "cwd:$(pwd) mychips:$mychips mysim:$mysim sites:$sites"; exit 0
 
 mkdir -p $pkidir				#Make sure certificates can be built
 if [ ! -f $pkidir/local.conf ]; then
@@ -171,7 +164,7 @@ function start_spa {
   	-v "$locdir/pki:/usr/local/devel/mychips/pki/local" \
   	-e "NODE_DEBUG=$NODE_DEBUG" \
   	-e "SITE=$n" \
-  	-- ${mysim}sim-c.sh spa; then
+  	-- ${mysim}/sim-c.sh spa; then
     echo "Failed starting MyCHIPs SPA server"; return
   fi
 }
@@ -192,7 +185,7 @@ echo "start_peer mach:$mach NODE_DEBUG:$NODE_DEBUG"
   	-v "$locdir/pki:/usr/local/devel/mychips/pki/local" \
   	-e "NODE_DEBUG=$NODE_DEBUG" \
   	-e "SITE=$n" \
-  	-- ${mysim}sim-c.sh peer; then
+  	-- ${mysim}/sim-c.sh peer; then
     echo "Failed starting MyCHIPs peer server"; return
   fi
 }
@@ -214,7 +207,7 @@ function start_model {
   	-e "NODE_DEBUG=$NODE_DEBUG" \
   	-e "SITE=$n" \
   	-e "MYCHIPS_DDHOST=mongo" \
-  	-- ${mysim}sim-c.sh model $(encode -m $modversion "$@"); then
+  	-- ${mysim}/sim-c.sh model $(encode -m $modversion "$@"); then
     echo "Failed starting MyCHIPs Agent-based Modeler"; return
   fi
 }
@@ -326,9 +319,9 @@ function start_log {
     y=$(expr $y + 22)			#Mac kludge: why does wish place differently than xterm?
   fi
   local geom="+$(expr $x + \( $n \* $xoff \))+$(expr $y + \( $n \* $yoff \))"
-#echo "start_log n:$n mach:$mach geom:$geom cmd:$cmd"
+#echo "start_log n:$n m:$mach g:$geom v:$logviewer cmd:$cmd"
   if [ "$logviewer" = logwin ]; then
-    wish logwin -geometry "$geom" -- $cmd &		#2>/dev/null (probably)
+    wish ${mypath}/logwin -geometry "$geom" -- $cmd &		#2>/dev/null (probably)
   
   elif [ "$logviewer" = xterm ] && which xterm >/dev/null; then
     xterm -T "$mach: $log" -geometry "$geom" -e /bin/bash -l -c "$cmd" &
@@ -376,7 +369,7 @@ function remote {
 
   cmdstrg="SITE=$SITE NODE_DEBUG=$NODE_DEBUG wsports=$wsports spaports=$spaports \
     newusers=$newusers admin=$admin dbname='$dbname' \
-    ${mysim}sim-c.sh $cmd $(encode "$@")"
+    ${mysim}/sim-c.sh $cmd $(encode "$@")"
 #echo "docker exec devel bash -c '$cmdstrg'"
   docker exec devel bash -c "$cmdstrg"
 }
